language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install xcffib"
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then python cairocffi/ffi_build.py; fi"
script: "py.test"
sudo: false
